### ISSUE TITLE
POST order with missing field yields 404 vs 400

### ISSUE THREAD

**Issue by fleupold** [cowprotocol/services#179] opened 2022-04-28 18:38 UTC
We received feedback from an integration that posting a bad request (ie with a missing mandatory field) to the order endpoint returns Not Found (instead of Bad Request)

This is probably related to way warp routing works. Not sure if it's worth fixing?

to repro
```
curl -X 'POST' \
  'https://barn.api.cow.fi/mainnet/api/v1/orders' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "sellToken": "0x6810e776880c02933d47db1b9fc05908e5386b96",
  "buyToken": "0x6810e776880c02933d47db1b9fc05908e5386b96",
  "receiver": "0x6810e776880c02933d47db1b9fc05908e5386b96",
  "sellAmount": "1234567890",
  "buyAmount": "1234567890",
  "validTo": 0,
  "appData": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "feeAmount": "1234567890",
  "kind": "buy",
  "partiallyFillable": true,
  "sellTokenBalance": "erc20",
  "buyTokenBalance": "erc20",
  "signature": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "from": "0x6810e776880c02933d47db1b9fc05908e5386b96"
}'
```

**Comment by vkgnosis** [comment] 2022-04-29 08:24
Like you said I think the way to fix it is to add a second handler to that path that doesn't validate the argument and returns an error always because we know the first matcher didn't get taken.

**Comment by nlordell** [comment] 2022-04-29 08:39
Another heavier option would be to switch to an alternative HTTP framework. I've recently heard good things of https://github.com/tokio-rs/axum is developed by the Tokio-rs team, and may not have the same issues as `warp` in this regard.

I'm not super fond of changing the framework we, unless there are other significant improvements it could provide, but it is another option that may be worth considering.

**Comment by vkgnosis** [comment] 2022-04-29 08:50
We can definitely do this in Warp so we don't have to switch. That said I've also had my eyes on Axum because Warp isn't that actively developed and we had some issues with it. Would be interested in prototyping how our api looks in Axum.

**Comment by nlordell** [comment] 2022-05-03 08:36
> That said I've also had my eyes on Axum because Warp isn't that actively developed and we had some issues with it.

This is the same reason I suggested this 😛. Also developed by the Tokio-rs team which I have lots of confidence in.

**Comment by Razz4780** [comment] 2023-02-10 14:15
> to repro
> 
> ```
> curl -X 'POST' \
>   'https://barn.api.cow.fi/mainnet/api/v1/orders' \
>   -H 'accept: application/json' \
>   -H 'Content-Type: application/json' \
>   -d '{
>   "sellToken": "0x6810e776880c02933d47db1b9fc05908e5386b96",
>   "buyToken": "0x6810e776880c02933d47db1b9fc05908e5386b96",
>   "receiver": "0x6810e776880c02933d47db1b9fc05908e5386b96",
>   "sellAmount": "1234567890",
>   "buyAmount": "1234567890",
>   "validTo": 0,
>   "appData": "0x0000000000000000000000000000000000000000000000000000000000000000",
>   "feeAmount": "1234567890",
>   "kind": "buy",
>   "partiallyFillable": true,
>   "sellTokenBalance": "erc20",
>   "buyTokenBalance": "erc20",
>   "signature": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
>   "from": "0x6810e776880c02933d47db1b9fc05908e5386b96"
> }'
> ```

Reproduction attempt results in `HTTP 400` and a nice message - ```Request body deserialize error: missing field `signingScheme` at line 16 column 1```. Seems like it's fixed now.

**Comment by vkgnosis** [comment] 2023-02-14 10:12
You're right that it seems to work but I actually couldn't quickly tell from the code why. I don't think this was an intentional change. I wonder if it works for all APIs.

**Closed** 2024-01-16 17:27 UTC
Labels: bug, good first issue
