### ISSUE TITLE
Refactoring Signature to accomodate the EIP-1271 support

### ISSUE THREAD

**Issue by elpiel** [cowprotocol/services#272] opened 2022-06-14 14:58 UTC
In the ongoing effort to add support for EIP-1271 Signature scheme (see #268 & #269) there has been a discussion on how to support the new Signature properly. I'm creating this issue in order to discuss different options on how this support can be implemented.

EIP-1271 is validated on-chain, which means that when creating order there must be an `eth_call` to validate the provided Signature with a mandatory `order.owner` (which is the contract address that should be called).
Until now it was possible to recover (`Signature::recover`) & validate the owner (`Signature::validate_owner`) off-chain but it becomes tedious to perform this validation and recovery on-chain in `Signature`.

`OrderCreation::verify_owner` can return an error while validating `expected_owner` (optional field passed through the order creation) and it seems reasonable to expect the same behavior for EIP-1271 signatures. However, mixing `Web3` specific implementations (or even knowledge of a services like `SignatureValidator`) with the `Signature`s seems to me like mixing 2 different responsibilities inside.

`OrderValidator::validate_and_construct_order` seems the right place for calling the `SignatureValidator` (added in #268) when an EIP-1271 signature is passed with the creation of an Order.

### API

`OrderCreation` should support all available signatures:

The `EIP-1271` signature requires a `eth_call` using the contract's address (the `order.from` on `OrderCreation` request) to validate that the signature is valid (`isValidSignature`) for the expected Order EIP-712 hash.
- EIP-712
- EthSign
- EIP-1271
- PreSign

`OrderCancellation` - At the moment `OrderCancellation` support only `EcdsaSignature` (EIP-712 & EthSign), however, it should for EIP-1271 it needs to support all Signatures except `PreSign`:
- EIP-712
- EthSign
- EIP-1271

`Signature` - is the "protocol signature" or in other words the signature representation as it is understood by the `GPv2Settlement` contract (so, it encodes some extra information such as the owner address for `PreSign` and `EIP-1271` signatures)

cc @nlordell let's discuss this issue before continuing on the final parts of the implementation.

**Comment by elpiel** [comment] 2022-06-28 07:53
Thanks for taking time to work on this @nlordell.
I saw that you performed E2E tests Rinkeby and that the features is feature-gated with CLI option.

Apart from #312 and the order cancellation, what else is left for the EIP-1271 support to be fully ready?

**Comment by nlordell** [comment] 2022-06-28 09:04
@elpiel - Before enabling it in production, we need a mechanism for computing additional fees resulting from the on-chain signature validation.

I think this is the biggest blocker for EIP-1271 (both #312 and order cancellation are incremental changes for complete EIP-1271 order support, but not required for actually enabling EIP-1271 orders).

**Comment by nlordell** [comment] 2022-07-05 11:44
> Is there such a mechanism for other calls in the service I can take a look at?

No, unfortunately this is quite unique.

> If not, what possibilities do you see to compute the additional fee?

I think that the client would have to provide an upfront `maxSignatureValidationGas`. That is, provide its own upper bound on how much gas it uses for signature validation. This upper bound would be added to the fee amount that gets computed. Then, the signature validator will have to check, not only that the `isValidSignature` returns the expected magic value, but that the gas cost of calling `isValidSignature` is less than this upper bound.

It might make sense to, in order:
1. start with hard-coded values
2. estimate this value by computing the `eth_estimateGas` for the `isValidSignature` call and then adding some fixed factor
3. allow user specified values via the `POST api/v1/quote` and `POST api/v1/orders` (giving fine-grained control to the clients) if they now the exact amount to use.

@vkgnosis - can you "sanity check" my idea, maybe you've also thought about this a bit and have some alternative solutions.

**Comment by vkgnosis** [comment] 2022-07-05 12:44
That does make sense to me. I'm wondering if it is possible without a user specified max gas amount. We need to be sure that the fee the user pays covers the gas cost. We could accomplish that by using the observed gas use from our simulation of the signature verification and then checking if with that gas value the fee is enough. I'm not sure what letting the user provide the maximum gas amount adds here.

**Comment by nlordell** [comment] 2022-07-05 13:41
> We could accomplish that by using the observed gas use from our simulation of the signature verification

This was the second step I suggested.

> I'm not sure what letting the user provide the maximum gas amount adds here.

The issue is that EIP-1271 is very much implementation specific. This means it is possible for there to be variance in the amount of gas required to verify signatures (i.e. gas at order placement != gas at auction time). To work around this, I thought it would make sense to simulate the `isValidSignature` and then add some "gas buffer" to account for the general case. However, since it is implementation specific, it could be that:
- The amount of gas is constant in all cases, so the buffer would be unnecessarily over-paying
- The amount of gas has a higher than normal variance (traversal through a linked list in storage for a convoluted example - but one that is legitimate because the Safe stores owners in a linked list for example, so its conceivable that signature verification may depend on this traversal). Then the client should be able to specify a higher upper bound so that they don't get excluded from auctions (on each auction we simulate the `isValidSignature` to ensure that it is still valid, here should also check that the signature still uses less gas than the order's upper bound).

**Comment by elpiel** [comment] 2022-07-14 11:50
Because I'm still trying to wrap my head around the whole concept, let me see if I'm following along.

From the code of the backend I see that there is the TRADE constant that mentions the `computeTradeExecutions` from `GPv2Settlement.sol`:
https://github.com/cowprotocol/services/blob/f7e53c3ba626cc71505b18b74e7abeb3df02f831/crates/shared/src/price_estimation/gas.rs#L13-L20

So I suppose because `computeTradeExecutions` calls the `recoverOrderFromTrade` which for EIP-1271 will call the `isValidSignature` of the contract and this needs to be estimated.

One thing I couldn't follow through the code was when the GPv2 settlement contract is called. I found a few places, like the 1Inch solver, that make a query to 1Inch for transfer of tokens from the GPv2 settlement contract.
I also found that the `solver::driver::Driver` uses the `GasPriceEstimating` & the `GPv2Settlement` contract and builds transactions to `GPv2Settlement` - > `settle`.

I suspect this is the main part you're referring to when talking about the gas estimation?
Let me know if I've missed anything else, but that's all I manged to find in the backend, especially if there are more places that need addressing.

**Comment by elpiel** [comment] 2022-07-25 13:44
@nlordell it would be great if you could look at my previous comment and tell me if I'm on the right track.
I can start working on it as soon as you confirm it

**Comment by nlordell** [comment] 2022-07-26 08:43
Hey, sorry for taking so long to get back to you, I've been away for the past couple of weeks.

> One thing I couldn't follow through the code was all the places where the GPv2 settlement contract is called and are related to the gas estimation we need to perform.

We use `eth_estimateGas` for this, so there is no need to change the code for actually submitting solutions (no changes to `solver` crate AFAICT).

The additional gas for EIP-1271 needs to be added when computing the minimum `feeAmount` for each order in the `orderbook` crate.

**Comment by nlordell** [comment] 2022-08-05 15:43
Hey @elpiel - I'm closing this issue because the signature refactor for EIP-1271 has already happened.

I created a separate issue https://github.com/cowprotocol/services/issues/420 for a more focused discussion on what is still required for fees.

**Closed by nlordell** 2022-08-05 15:43 UTC
